engines:
   radon:
     enabled: true
   pep8:
     enabled: true
   duplication:
     enabled: true
     exclude_fingerprints:
       # clone due to similar help text
       - 750894054fd499d62428eea3e635397a
     config:
       languages:
       - python

ratings:
   paths:
   - "**.py"

exclude_paths:
- "openach/migrations/*"
- "openach/tests.py"

