language: python

python:
  - "3.5"

install:
  - pip install -r requirements.txt
  - pip install coveralls coverage
  - npm install

script:
  - python manage.py collectstatic --no-input
  - python manage.py check --fail-level=WARNING
  - python manage.py test
  - coverage run --source='.' manage.py test

after_success:
  - coveralls
